### ISSUE TITLE
MacOS builds?

### ISSUE THREAD

**Issue by chmaha** [SpotlightKid/dfzitarev1#3]
Is it possible to build dfzitarev1 for MacOS?

**Comment by SpotlightKid** [comment]
Yes, it is possible, a simple `make` (or `make BUILD_VST2=true` for VST2) should do. But I don't plan to provide binaries for macOS myself, sorry.

**Comment by chmaha** [comment]
Great thanks!

**Comment by chmaha** [comment]
And confirm building on the Mac works perfectly (after installing command line build tools via `xcode-select --install`)!

**Comment by SpotlightKid** [comment]
Great to hear, thanks!
