### ISSUE TITLE
Hide certain sliders?

### ISSUE THREAD

**Issue by chmaha** [SpotlightKid/dfzitarev1#4]
Would you be able to help me figure out how to hide certain sliders in the generic UI? Specifically I wanted to create a very simple version of the plugin without the two EQs and without a level control. I figured out how to set default values but I don't want the user to be able to change them.

**Comment by SpotlightKid** [comment]
Unfortunately that's not straightforward, because the FAUST code for the plugin uses the FAUST library `dm.zita_rev1` demo function, which pre-defines all parameters and sliders.

You would have to copy that function (from `/usr/share/faust/demos.lib`, if you have FAUST installed) into `faust/dfzitarev1.dsp` and adapt it to replace the parameters, which you don't want, with constants. You will need at least basic knowledge of the FAUST DSP language for that.

**Comment by chmaha** [comment]
Thanks, I will experiment with that!

**Comment by SpotlightKid** [comment]
Maybe it would be easier to just provide built-in presets with the settings you like?

See [here](https://github.com/SpotlightKid/dfzitarev1/blob/master/plugins/dfzitarev1/PluginDFZitaRev1.hpp#L131) for the preset definitions.

**Comment by chmaha** [comment]
Thanks, I like the challenge of modifying the Faust and even with presets, users could change EQ etc. For example, the original ladspa (and JACK) versions of zita-rev1 didn't have a level control.

**Comment by SpotlightKid** [comment]
EQ param definitions start here:

https://github.com/grame-cncm/faustlibraries/blob/4031a3c8406fc6df45d72163464fecaa59ac99e9/demos.lib#L851

**Comment by sletz** [comment]
Note that if you fix some of the parameters, an interesting property of the Faust compiler is to compute all what depends of those parameters at compile time, thus producing more efficient code.

**Comment by chmaha** [comment]
I suppose the only sticking point is pasting in that code into `faust/dfzitarev1.dsp` and knowing what to do with the `process = _,_ : dm.zita_rev1 : _,_;` part etc. I think the modifying of zita-rev1 part should be fine.

**Comment by SpotlightKid** [comment]
Correct. Of course, if you change the `faust/dfzitarev1.dsp` file, you need `faustpp` and FAUST to re-generate the plugin DSP code.

**Comment by chmaha** [comment]
Completed the task (I think). The compiled plugin works as expected:
![image](https://user-images.githubusercontent.com/120390802/211215395-c19c4bf3-9849-45a1-bd8e-ad80d0fd03ee.png)

Thanks for your help!

**Comment by SpotlightKid** [comment]
Cool. If you distribute this, I would like to ask you to change the plugin name, ID and URI, though.

**Comment by chmaha** [comment]
Yes, of course...I was in the midst of doing that and now I seem to have broken the make ;)

**Comment by chmaha** [comment]
OK, fixed again...Is this what you meant:
![image](https://user-images.githubusercontent.com/120390802/211223906-68dacd92-aa0e-4199-8e5b-f5dde9f0f3ff.png)
Is there a special thing I need to do with regard name, ID and URI beyond change them to taste?

**Comment by SpotlightKid** [comment]
No, you can use what you see fit.

**Comment by chmaha** [comment]
Thanks for all your help again. On topic, I managed to hide the VST3 "Current Program" slider (a distrho default?) by commenting out various sections. The slider didn't seem to work for me even _with_ your presets available so it was good to remove it for the things I'm doing that don't require presets.

**Comment by SpotlightKid** [comment]
I don't think VST3 format has support for builtin presets in DPF (yet?). VST2 format supports them and for LV2 they are just converted into a `presets.ttl` file included in the plugin bundle dir.

**Comment by chmaha** [comment]
Thanks for the info!
