### ISSUE TITLE
Statically build?

### ISSUE THREAD

**Issue by chmaha** [SpotlightKid/dfzitarev1#5]
I'm on Arch so the very little I understand about statically linking libraries tells me that Arch makes it quite difficult by default. Do you think I'd have luck building DPF plugins on a old Ubuntu LTS release where I could at least be moderately confident that version numbers of libraries would generally be higher on most people's machines? Or, on an Ubuntu release, is statically linking more trivial with the DPF build system? I did see some static build flags in `Makefile.base.mk` but I'm not convinced it did much of anything. I'm simply looking to provide Linux binaries as part of releases without having to provide multiple to cover all the distro bases.

And on a related note, as I mentioned in the other issue thread, I and others have successfully built on MacOS but I assume those binaries are not statically linked (unlike the Windows script builds). I assume I'm in luck that I'm building on a 2014 or so MacBook Air that can't access latest OS so, again, library numbers would only go up for most people. Maybe I'm not understanding this correctly :)

**Comment by SpotlightKid** [comment]
By default, DSP plugin binaries are only dynamically linked against standard C and C++ libs. I'm not sure how to statically link them and if that would make sense.

It's probably best to ask DPF's author, @falkTX, about these things.

**Comment by chmaha** [comment]
I'll reach out to @falkTX...thanks again!
